### ISSUE TITLE
redux-bike-router

### ISSUE THREAD

**Issue by caesarsol** [thinkloop/state-driven-routing#1]
Hello Baz,
I just released a project with an approach so similar to your recent article "State-Driven Routing". We were actually having the same problem in parallel!
I thought you may be interested in the library I extracted from it: [redux-bike-router](https://github.com/accurat/redux-bike-router)

(I actually find our approach more powerful and open to modifications than react-router)
Let me know what you think!

cesare

**Comment by thinkloop** [comment]
Very interesting! I like these lines:

> This forces you to redesign a lot of your code for every small routing change, because your components are now tightly coupled to the routing solution.
> 
> It can be added whenever you want in the lifetime of the project.

This is very much at the core of why I prefer state-driven routing.

In your [example](https://github.com/accurat/redux-bike-router/blob/master/example/src/App.js) you use divs for the links, which means that the url doesn't have to be pre-generated to show on hover or to handle ctrl+clicking and stuff. Does the solution also work with regular `<a>`? If it weren't for the need to pre-calculate urls, state-driven routing would be even better since you wouldn't need a special `updateURL` type action, and instead just have regular actions that then generate urls from state.

**Comment by caesarsol** [comment]
Thanks! yes, that prototype does not yet support regular <a> links (and ctrl+clicking and such), I would have to come out with a way to pre-generate urls.
Do you feel the need for that feature? I ended up for not using them because of the kind of applications I build.
(I'm not sure I understood if this is your point though :) )

**Comment by thinkloop** [comment]
> (I'm not sure I understood if this is your point though :) )

Yes that was exactly my point :) Having links work normally is generally a requirement for many apps, but if you can get away without it, there are some very nice advantages.

**Comment by caesarsol** [comment]
I should get around the issue by generating the URL from the state after changing the right segment in isolation. Every link would then need only the info that are not in the state.

**Comment by thinkloop** [comment]
> changing the right segment in isolation

I considered this as well, how would you do it? One option is to have a second redux that makes the change, generates the url, then shuts down. Might be ok, but feels heavy. Any other ideas?

**Comment by caesarsol** [comment]
Yeah that's absolutely right. Might not be as heavy as iy seems though, let me make a couple of tests.
